### ISSUE TITLE
`import.meta` is empty

### ISSUE THREAD

**Issue by zyxkad** [vitejs/vite-plugin-vue#126]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [X] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

`import.meta` is empty in `vite.config.js`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9nh16s?file=vite.config.js

### Steps to reproduce

```js
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

// https://vitejs.dev/config/
export default defineConfig(async ( command, mode ) => {
	console.log(import.meta);
	console.log(import.meta.env.DEV);

	return {
		plugins: [vue(), vueJsx()],
		base: '/',
		resolve: {
			alias: {
				'@': fileURLToPath(new URL('./src', import.meta.url))
			}
		},
	}
})
```

But the `import.meta.env` is defined in <https://cn.vitejs.dev/guide/env-and-mode.html>

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
```

### Used Package Manager

npm

### Logs

```

▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    vite.config.js:9:13:
      9 │   console.log(import.meta);
        ╵               ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    vite.config.js:10:13:
      10 │   console.log(import.meta.env.DEV);
         ╵               ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.

{}
failed to load config from /Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/vite.config.js
error during build:
TypeError: Cannot read properties of undefined (reading 'DEV')
    at /Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/vite.config.js:43:31
    at loadConfigFromFile (file:///Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62225:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61843:28)
    at async build (file:///Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44512:20)
    at async CAC.<anonymous> (file:///Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/PluginWebPoint/vue-project/node_modules/vite/dist/node/cli.js:813:9)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
This is expected. `import.meta.env` is not support in config files.
That document describes the feature for project files.

See https://cn.vitejs.dev/config/#using-environment-variables-in-config for how to use env vars in config files.
