### ISSUE TITLE
Add API generator as JSON meta files

### ISSUE THREAD

**Issue by jourdain** [vitejs/vite-plugin-vue#239]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Description

As a developer using Vite and Vue, I would love to see a plugin that would be able to extract the API of my components and expose them in a standard way using some kind of JSON/YAML files.

Basically I would love to see a standard emerge that capture similar information as you can see with [vuetify](https://unpkg.com/browse/vuetify@3.3.11/dist/json/web-types.json) or [quasar](https://unpkg.com/browse/quasar@2.12.3/dist/api/) but ideally such API description should become a standard rather than a custom format for each library.

Also ideally once such format became a standard, we could envision website generators using that as input for API documentation. 

### Suggested solution

- [vuetify](https://unpkg.com/browse/vuetify@3.3.11/dist/json/web-types.json) example format
- [quasar](https://unpkg.com/browse/quasar@2.12.3/dist/api/) example format

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jourdain** [comment]
Sorry for the cross posting but I initially suggested [here](https://github.com/vitejs/vite/issues/14035) in the vite project. But it better match the vue plugin...

**Comment by sxzz** [comment]
Thanks for your idea. We actually already have [`vue-component-meta` in Volar](https://github.com/vuejs/language-tools/tree/master/packages/vue-component-meta). 

I think it would be better to have this feature in the community project than in the official plugin for now.

**Comment by jourdain** [comment]
Thanks for the pointer. I'm still not sure how to use it on existing vue.js bundles but definitely a step toward the end goal.

Ideally, I would love to see it become a standard practice, hence having it provided at the core would help the adoption unless similar capabilities could be derived from a generated umd. 

To be fully transparent, I'm looking to streamline the integration process of any vue.js library out there into a [trame](https://kitware.github.io/trame/) component by generating the corresponding Python code via [some automation tool](https://trame.readthedocs.io/en/latest/tools.widgets.html). So anything that could extract props/events/docs/directive information into a usable form would go a long way... 

Thanks again for getting back to me about that suggestion.
