### ISSUE TITLE
[WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

### ISSUE THREAD

**Issue by Unkrass** [vitejs/vite-plugin-vue#257]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

I upgraded from vue-cli to vite and when I start the application I get the following vite output warning for every time I use `import.meta` in my vite.config.js.

```
[WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    vite.config.js:9:2:
      9 │   import.meta.env = {...import.meta.env, ...loadEnv(mode, process.cwd())};
        ╵   ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.
```
I would like to know where to set the output format to "esm".

I tried setting the targets as suggested [here](https://github.com/vitejs/vite/issues/10167), but the warning still doesn't disappear.

If you need me to add more data to the reproduction repo, please let me know.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-8pkm7u?file=vite.config.js,package.json,src%2FApp.vue&terminal=dev

### Steps to reproduce

`yarn serve`
or
`vite`

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 10.91 GB / 15.60 GB
    Container: Yes
    Shell: 5.8.1 - /opt/distrod/alias/usr/bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    @vitejs/plugin-vue: ^4.3.4 => 4.3.4 
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Unkrass** [comment]
Apparently my node version reset itself every time I opened a new console and now that I fixed that, the warnings are gone. I'm sorry
