### ISSUE TITLE
vite-plugin-require-transform  don't work

### ISSUE THREAD

**Issue by qiancheng900801** [vitejs/vite-plugin-vue#369]
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Describe the bug

vite :   const Buffer = require('safe-buffer').Buffer; console.log(Buffer);   //undefined
webpack or node:  const Buffer = require('safe-buffer').Buffer; console.log(Buffer);  // Buffer
why?

### Reproduction

https://vitejsvite8tnkvo-bed1--5173--810981ba.local-credentialless.webcontainer.io/

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 1.38 GB / 15.63 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nvm\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nvm\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.5.2 => 4.6.2
    vite: ^5.0.12 => 5.1.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-vue/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-vue/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
```[tasklist]
### Tasks
```

**Comment by sapphi-red** [comment]
This is not the repository of vite-plugin-require-transform.
